show better stack trace for commands (#3565)
## Proposed changes

As described here #3534 current stack trace for element commands, custom commands and waitUntil are pretty much useless for end user as far as there is no line of test it was called in.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Tested with sync and async/await modes.

Here are some examples

```
Error: for test
    at Object.<anonymous> (/path-to/sources/e2e/src/wdio/commands.ts:21:9)
    at /path-to/sources/e2e/src/wdio/commands.ts:7:71
    at Browser.browser.addCommand (/path-to/sources/e2e/src/wdio/commands.ts:20:46)
    at Browser.next [as shouldThrow] (/path-to/sources/e2e/node_modules/webdriver/build/monad.js:120:27)
    at Context.<anonymous> (/path-to/sources/e2e/test/specs/debug/debug.spec.ts:27:13)
```
---
```
Error: element ("waiter") still not existing after 1ms
    at timer.catch.e (/path-to/sources/e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:68:13)
    at Element.waitForExist (/path-to/sources/e2e/node_modules/webdriverio/build/commands/element/waitForExist.js:45:15)
    at Context.<anonymous> (/path-to/sources/e2e/test/specs/debug/debug.spec.ts:35:17)
```
---
```
Error: Promise was rejected with the following reason: Error: timeout
    at timer.catch.e (/path-to/sources/e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:71:11)
    at Context.<anonymous> (/path-to/sources/e2e/test/specs/debug/debug.spec.ts:40:13)
```
---
```
Error: Can't call optAttribute on element with selector "attr" because element wasn't found
    at Context.<anonymous> (/path-to/sources/e2e/test/specs/debug/debug.spec.ts:47:15)
```
---
```
Error: Promise was rejected with the following reason: Error: throw exception in wait until
    at timer.catch.e (/path-to/sources/e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:71:11)
    at Context.<anonymous> (/path-to/sources/e2e/test/specs/debug/debug.spec.ts:52:13)
```

### Reviewers: @webdriverio/technical-committee