Add missing ; before (
Without the `;` running the tutorial would result in this error:

    TypeError: require(...) is not a function

If every single `;` is to be eradicated, you can use `!`, `~` or `void` instead.