fix the scroll error when using mobile browser
When using scroll with out a selector.the callback in Q() object will get the wrong "this",therefor cause a TypeError "this.touchScroll is not a function".
bind this will fix it.

Former-commit-id: 5a4ed08c9904a5799022a25219d04e1a6605eb24