Bug #12094 - Fix _appiumStart method (#12095)
* Allure Reporter Improvements. Adding support to fixtures for mocha/jasmine. Update the Cucumber Step Mode.

Change constants and option names.

* Fix test:depcheck in packages/wdio-allure-reporter/src/state.ts

* Fixes:
- using 'getErrorFromFailedTest' to format error messages

* Fixes:
- removing unnecessary code for mocha and jasmine

* Fixes:
- eslint and spaces before from.

* Fixes:
- Property 'labels' does not exist on type 'ExecutableItem'.
- error TS2835: Relative import paths need explicit

* Fixes:
- Allure Report Methods.
- Eslint Fixes
- Test Cases wdio-allure-reporter related

* Fixes:
- Fix undefined in fixtures

* Update packages/wdio-allure-reporter/tests/allureFeatures.test.ts

* Fixes:
- Fixes (base on comments)
- import check
- eslit command executed
- npm run test command executed
- no it.only in the commit

* Fixes:
- Option name rollback - comment left
- Option for customized the test error when hook fails (put off for next ticket)

* Fixes:
- bad merge from main (imports)

* Fixes:
- Separate hook and test status getter
- review of test cases for fixtures.
- fixtures cannot be failed the worst status could be broken.

Signed-off-by: Manuel Lara <lararojas.mr@gmail.com>

* Git #12094
The _startAppium is stucking whitout timeout when the promise emit 'data' but the data not includes the specific text.

I've set a timeout y default in 60sec by security, and implemented a validation to reject only once at the first failure.

Add some comments.

* Removing all allure changes. They were sending to other branch.

* Validating resolve in case that the stdio has non error messages, like debugger messages, etc. The message is log as warning, and the event is resolve.

* Removing semicolons from code.

* Resolving the promise

* unit tests for timeout new parameter

Signed-off-by: Lara, Manuel <lararojas.mr@gmail.com>

* fixes unit test - appium service

Signed-off-by: Lara, Manuel <lararojas.mr@gmail.com>

* Update packages/wdio-appium-service/src/launcher.ts

Co-authored-by: Christian Bromann <git@bromann.dev>

* Update packages/wdio-appium-service/src/launcher.ts - Type

Co-authored-by: Christian Bromann <git@bromann.dev>

* Create a const for timeout and set the timeout in 30 sec by default.

Signed-off-by: Lara, Manuel <lararojas.mr@gmail.com>

* Fix eslint errors.

Signed-off-by: Lara, Manuel <lararojas.mr@gmail.com>

* Fix test cases, changes in the method to cover all missing cases.

Signed-off-by: Lara, Manuel <lararojas.mr@gmail.com>

---------

Signed-off-by: Manuel Lara <lararojas.mr@gmail.com>
Signed-off-by: Lara, Manuel <lararojas.mr@gmail.com>
Co-authored-by: Christian Bromann <git@bromann.dev>