Increase timeout since exact millisecond is not guarantee (#15572)
Fix below instability
```
 FAIL  packages/wdio-runner/tests/reporter.test.ts > BaseReporter > it should fail if waitForSync times out
AssertionError: promise resolved "true" instead of rejecting

- Expected:
Error {
  "message": "rejected promise",
}

+ Received:
true

 ❯ packages/wdio-runner/tests/reporter.test.ts:319:44
    317|         // @ts-ignore test reporter param

    318|         setTimeout(() => (reporter['_reporters'][0].inSync = true), 11…
 Test Files  1 failed | 351 passed (352)
    319|         await expect(reporter.waitForSync())
      Tests  1 failed | 3955 passed | 7 skipped (3963)
       |                                            ^
Type Errors  no errors
   Start at  15:13:21
    320|             .rejects.toEqual(new Error('Some reporters are still unsyn…
    321|     })