Add missing default export of ESLint plugin
This change fixes the following error on importing wdio config to ESLint flat config:
> SyntaxError: The requested module 'eslint-plugin-wdio' does not provide an export named 'default'