webdriverio: user friendly waitUntil messages (#3571)
## Proposed changes

Make waitUntil messages more user friendly, no more frightening "Promise was rejected" :)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

examples

```
Error: waitUntil condition timed out after 60ms
     at timer.catch.e (/.../e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:71:13)
```
```
Error: waitUntil user message
     at timer.catch.e (/.../e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:69:17)
```
```
Error: waitUntil condition failed with the following reason: user exception in waitUntil
     at timer.catch.e (/.../e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:74:11)
```

### Reviewers: @webdriverio/technical-committee