Properly implement 'setTimeout' function and /timeouts endpoints (#3215)
## Proposed changes

* Address incorrect parameters/return definition for __/session/:sessionId/timeouts__ endpoint.
* Rename `setTimeout` command to `setTimeouts` to be consistent with `getTimeouts`.
* Introduce unified `setTimeout` browser command that proxies values to respective `setTimeouts` command, which takes different parameters depending on protocol.

Fixes #3214.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments
Initially reverted changes made in 690fd66f02678e76270b333acbd99393c4afc3cd, due to the fact that it initially not even recognized ["Object" type](https://github.com/webdriverio/webdriverio/blob/972e66725ae71e1bb9c235b5c3dad304d1506827/packages/webdriver/protocol/webdriver.json#L59) when [validating parameters against "object" type](https://github.com/webdriverio/webdriverio/blob/972e66725ae71e1bb9c235b5c3dad304d1506827/packages/webdriver/tests/utils.test.js#L30-L42), which is apparently case sensitive.

In Firefox and Safari this command:
```js
browser.setTimeout({ script: 1000 })
```
Would result in the following error:
```
Error: Malformed type for "timeouts" parameter of command setTimeout
Expected: Object
Actual: object

For more info see https://w3c.github.io/webdriver/webdriver-spec.html#dfn-timeouts

    at Browser.<anonymous> (/Users/profile/.npm/lib/node_modules/webdriverio/node_modules/webdriver/src/command.js:55:23)
    at /Users/profile/project/webdriverio.js:15:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Noticed later on that Chrome actually also does not work with the above mentioned command, due to the fact that JsonWireProtocol takes different parameters than the W3C definition.
```
Error: Wrong parameters applied for setTimeout
Usage: setTimeout(type, ms)

Property Description:
  "type" (string): The type of operation to set the timeout for. Valid values are: "script" for script timeouts, "implicit" for modifying the implicit wait timeout and "page load" for setting a page load timeout.
  "ms" (number): The amount of time, in milliseconds, that time-limited commands are permitted to run

For more info see https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtimeouts

    at Browser.<anonymous> (/Users/profile/.npm/lib/node_modules/webdriverio/node_modules/webdriver/src/command.js:33:19)
    at /Users/profile/project/webdriverio.js:15:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Based on that I've decided to rename `setTimeout` to `setTimeouts` and introduce a unified `setTimeout` (proxy) command, which works with both protocols.

### Reviewers: @webdriverio/technical-committee